import {HighlightStyle, tags} from "@codemirror/highlight"
export const highlightStyle = HighlightStyle.define([
  {tag: tags.link, class: "cm-link"},
  {tag: tags.heading, class: "cm-heading"},
  {tag: tags.emphasis, class: "cm-emphasis"},
  {tag: tags.strong, class: "cm-strong"},
  {tag: tags.keyword, class: "cm-keyword"},
  {tag: tags.atom, class: "cm-atom"},
  {tag: tags.bool, class: "cm-bool"},
  {tag: tags.url, class: "cm-url"},
  {tag: tags.labelName, class: "cm-labelName"},
  {tag: tags.inserted, class: "cm-inserted"},
  {tag: tags.deleted, class: "cm-deleted"},
  {tag: tags.literal, class: "cm-literal"},
  {tag: tags.string, class: "cm-string"},
  {tag: tags.number, class: "cm-number"},
  {tag: [tags.regexp, tags.escape, tags.special(tags.string)], class: "cm-string2"},
  {tag: tags.variableName, class: "cm-variableName"},
  {tag: tags.local(tags.variableName), class: "cm-variableName cm-local"},
  {tag: tags.definition(tags.variableName), class: "cm-variableName cm-definition"},
  {tag: tags.special(tags.variableName), class: "cm-variableName"},
  {tag: tags.typeName, class: "cm-typeName"},
  {tag: tags.namespace, class: "cm-namespace"},
  {tag: tags.macroName, class: "cm-macroName"},
  {tag: tags.definition(tags.propertyName), class: "cm-propertyName"},
  {tag: tags.operator, class: "cm-operator"},
  {tag: tags.comment, class: "cm-comment"},
  {tag: tags.meta, class: "cm-meta"},
  {tag: tags.invalid, class: "cm-invalid"},
  {tag: tags.punctuation, class: "cm-punctuation"},
  {tag: tags.modifier, class: "cm-modifier"},
  {tag: tags.function(tags.definition(tags.variableName)), class: "cm-function cm-definition"},
  {tag: tags.definition(tags.className), class: "cm-class cm-definition"},
  {tag: tags.operatorKeyword, class: "cm-operator"},
]);